### PR TITLE
add promtail and loki

### PR DESCRIPTION
**Pull request by weslayer**

### CODE REVIEW

**Comment by weslayer** [comment]
brb this kinda hard 😭

**Comment by weslayer** [comment]
@evanugarte need nginx to be pushed when u have time 😎

**Comment by evanugarte** [comment]
@weslayer https://github.com/SCE-Development/poweredge-nginx

**Comment by evanugarte** [comment]
closing because as of now, loki is causing the server to freeze completely and we haven't figured out why

**Pull request closed without merging**
